version: '3'


vars:
  R_DEV: "/opt/R/R460/lib/R/bin/R"
  R_HIGHS_LIB_DIR: "/home/f/lib/highslib"


tasks:
  compile_attributes:
    cmds:
      - R -e 'Rcpp::compileAttributes(".")'

  docs:
    cmds:
      - R -e 'library("roxygen2"); roxygenize(".", c("rd", "namespace"), load_source)'

  build:
    cmds:
      - task compile_attributes
      - task docs
      - R CMD build .

  inst:
    cmds:
      - task build
      - R CMD INSTALL highs_*.tar.gz

  check:
    cmds:
      - task build
      - R CMD check highs_*.tar.gz

  cran_check:
    cmds:
      - task build
      - R CMD check --as-cran highs_*.tar.gz

  dev_compile_attributes:
    cmds:
      - "{{.R_DEV}} -e 'Rcpp::compileAttributes(\".\")'"

  dev_build:
    cmds:
      - task dev_compile_attributes
      - task docs
      - "{{.R_DEV}} CMD build ."
    
  dev_inst:
    cmds:
      - task dev_build
      - "{{.R_DEV}} CMD INSTALL highs_*.tar.gz"

  dev_check:
    cmds:
      - task dev_build
      - "{{.R_DEV}} CMD check highs_*.tar.gz"

  readme:
    cmds:
      - R -e 'rmarkdown::render("README.Rmd", clean = FALSE)'
      - pandoc README.md -s --highlight-style=pygments -o README.html

  manual:
    cmds:
      - task clean
      - R CMD Rd2pdf --output=Manual.pdf .

  clean:
    cmds:
      - rm -f Manual.pdf README.knit.md README.html
      - rm -rf .Rd2pdf*
      - rm -rf highs.Rcheck

  remove_highslib:
    cmds:
      - rm -rf "{{.R_HIGHS_LIB_DIR}}"

  winbuilder_check_devel:
    cmds:
      - task build
      - R -e "devtools::check_win_devel(email = 'FlorianSchwendinger@gmx.at')"

  highs_build:
    cmds:
      - bash inst/build_highs.sh

